#!/usr/bin/env python

from SCons.Script import ARGUMENTS, Default, Glob, SConscript, VariantDir

EXTENSION_NAME = "dao"
GODOT_PROJECT_DIR = "../dao"
GODOT_API_VERSION = "4.6"

if "api_version" not in ARGUMENTS and "custom_api_file" not in ARGUMENTS:
    ARGUMENTS["api_version"] = GODOT_API_VERSION

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["src"])

object_dir = "build/src{}".format(env["suffix"])
VariantDir(object_dir, "src", duplicate=0)
sources = Glob("{}/*.cpp".format(object_dir))
target_path = "{}/bin/{}{}".format(GODOT_PROJECT_DIR, EXTENSION_NAME, env["suffix"])

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "{}.framework/{}".format(target_path, EXTENSION_NAME),
        source=sources,
    )
elif env["platform"] == "ios":
    library = env.StaticLibrary("{}.a".format(target_path), source=sources)
else:
    library = env.SharedLibrary(
        "{}{}".format(target_path, env["SHLIBSUFFIX"]),
        source=sources,
    )

env.NoCache(library)
Default(library)
